### ISSUE TITLE
Question for Environment and Dataset Setup

### ISSUE THREAD

**Issue by zahir-w** [clear-nus/octopi#1]
Hi, when I followed the instructions in the Environment and Dataset Setup, I got some error.
```command
$ python utils/generate_qa.py --data_path path/to/processed/data  # Generate question-answer pairs for tactile feature alignment and end-to-end fine-tuning
```
it seems that some code in `generate_qa.py` needs a change.

### line 137
```Python
sample = random.sample(samples.keys(), k=num_tactile)[0]
```
need to be

```Python
sample = random.sample(list(samples.keys()), k=num_tactile)[0]
```
---
### line 155
```Python
all_samples = random.sample(samples.keys(), k=num_tactile)
```
need to be

```Python
all_samples = random.sample(list(samples.keys()), k=num_tactile)
```

Best regrads,
Zahir Wang

**Comment by SamsonYuBaiJian** [comment]
Hi Zahir, thank you for taking the time raise these errors and for the corrections! I've pushed an updated version with your corrections.
